### ISSUE TITLE
FTP showing sorry, this file has changed outside ICEcoder

### ISSUE THREAD

**Issue by hopgoodpaul** [icecoder/ICEcoder#692]
When connecting to a localhost FTP server on a Raspberry Pi I get the error message saying the file changed outside of ICEcoder.

New files are created and edited just fine.

When I run a flask local web server (port 5000) the files then become non-editable for some reason.

**Comment by mattpass** [comment]
@hopgoodpaul This would likely be due to a false positive mismatch on modified datetimes on the files (or a lack of datetimes) vs what ICEcoder thinks is last the datetime known. I'll look into what I can do to tweak that and avoid this.

**Comment by hopgoodpaul** [comment]
I think you're right about the datetimes on the files.

I've got it working temporarily by removing the filemtime assignment of 1000000 in lib/file-control-xhr.php

`$filemtime = !isset($ftpSite) && $serverType=="Linux" ? filemtime($file) : filemtime($file); 
 //"1000000";`

I can now continue working with it like this but obviously it's not a permanent fix.

Thanks very much

**Comment by mattpass** [comment]
That'd be it and a fix, yep. I put that in as Windows files don't have a modified datetime, so using 1000000 as a fallback, but it's obviously causing a mismatch issue. Will look into a proper fix for this 👍

**Comment by hopgoodpaul** [comment]
Awesome! Thanks again.

**Comment by digitart** [comment]
**hopgoodpaul** solution worked for me in ftp servers WITH A DIFFERENT IP ADDRESS that the one I have installed icecode. Anyway I still get an error if I try to see "Properties" from the right menu over files:

`"Sorry - problem with file/folder requested"`

On the other hand, I've installed ICEcoder on one of the domains of my server. If I set up FTP for another domain on the same box/ip address I can see the list of files on the domain, open any of them but can't save any changes, nor modify names nor create a new filer/directory.
Even if I change file premissions to 777 (or any other combination, using an external ftp client) file can't be saved.

I presume that in some way ICEcoder is seeing this files as "localhost" files so, instead of use FTP user to write them, it is trying to save them as "nobody" wich is obvious impossible:

`"Sorry, could not write gtplastics/about.html at demosx.ml"`

I've donated already to get my license and have no problem with it, but with this issues ICEcoder is pretty unusable for me by now :/

**Comment by mattpass** [comment]
@digitart I'll look into this issue also, does sound like it's considering it to be local as you suggest and likely also a perms issue.

**Comment by steelandt** [comment]
Unfortunatly, I have the same issue. I've installed ucecoder as subdomain on my webserver and use the ftp to connect to other subdomains. If I save, doesn't work (same error message). I can recopy the code from right to left pane and then the save works. However, then when I later open the file, the code is double (appart from the first line), making the code invalid :(

**Comment by steelandt** [comment]
Also, when relading, the right pane doesn't find the content of the file anymore: saying 'No data'.

**Comment by mattpass** [comment]
@steelandt The double line issue should be fixed by commits in this repo, the official v6.0 beta is a little behind and contains the issue.

**Comment by steelandt** [comment]
OK, thanks for the update.

**Comment by digitart** [comment]
Hi, Still having problems with FTP here. I've just downloaded current repo, and reinstalled from zero. I still have the problem with ftp's that share same IP address (i.e. other domains on my same server). I can login, get the files, edit them, but when trying to save I see that ICEcoder is trying to save it as a local file under the ICEcoder intallation, wich obvously doesn exists. ICEcoder still presume that ftp with same IP address = local installation. Do you have a EAT for a fix to this problem?
![captura de pantalla de 2017-05-13 20 56 36](https://cloud.githubusercontent.com/assets/866228/26031101/cfa10e1a-382c-11e7-81a0-1de58fbc9e79.png)

**Comment by steelandt** [comment]
Hi Matt, downloaded this repo and tested it again, but still the same issue. I'm running also on one server with the dame IP. Icecoder is hosted on a subdomain and with the ftp I'm connecting to another subdomain on the same server. 
When saving, it gives me the same error. However, the path is wrong since I see first the subdomain name of the domain where ICECODER is running from (devadmin) and then the subdomain that I'm trying to edit (davidsfonds):
![afbeelding](https://cloud.githubusercontent.com/assets/28605263/26032287/d8da6e0a-388f-11e7-92ae-53053210c739.png)
Probably this could explain the bug.

**Comment by marcoczen** [comment]
Yep - I just installed the 6.0 beta from github and this issue still persists ...

**Comment by marcoczen** [comment]
Update - Note that I am not using FTP. And the client is a Linux Box ( server is Linux as well ).

**Comment by marcoczen** [comment]
Update  -> IceCoder - Keeps adding code duplicates ( entire lines ) - Issue 714 , 715 related #716

From @mattpass ;

The line in question is likely 265 of lib/file-control-xhr.php:

if (!(isset($_GET['fileMDT']))||$filemtime==$_GET['fileMDT']) {
You could try changing that to:

if (!(isset($_GET['fileMDT']))||$_GET['fileMDT']=="1000000"||$filemtime==$_GET['fileMDT']) {

**Comment by paulfeakins** [comment]
This happens for me in version 6.0 over FTP. I downloaded recently from the website. It seems this issue has been open for nearly 2 years?

**Comment by paulfeakins** [comment]
Tested and also happens in the master branch from github - makes me wonder if this project is active as both the download from the website and the master branch on github have fatal bugs out the box?

**Comment by mattpass** [comment]
@paulfeakins it is still active but not worked on as much as I'd like due to lack of spare time. It's open source though, so feel free to get involved!

**Comment by paulfeakins** [comment]
I know the feeling! I will see what I can do as I believe this is currently the only open source, web based IDE with remote FTP functionality, so I think it could become extremely popular if the blockers were fixed.

**Comment by mattpass** [comment]
Have decided to remove FTP from ICEcoder as it's just not a modern solution to data transfer these days. Far better solutions out there and can be part of ICEcoder in future.
